import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Get the boook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="relative p-10 text-2xl text-center overflow-hidden">
          {/* Video background */}
          <video
            className="absolute top-0 left-0 w-full h-full object-cover"
            autoPlay
            muted
            loop
          >
            <source
              src="https://www.w3schools.com/html/mov_bbb.mp4"
              type="video/mp4"
            />
            Your browser does not support the video tag.
          </video>

          {/* Overlay */}
          <div className="absolute inset-0 bg-black opacity-50"></div>

          {/* Text */}
          <div className="relative z-10 text-2xl font-black text-white">
            Don&apos;t remember the name of the Book? Don&apos;t worry, we got
            you!
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
